#!/usr/bin/python3
import sys
import netifaces as ni

CHEATSHEET_PATH = '/pt/references/cheatsheet'

def get_ip_address(interface):
    try:
        ip_address = ni.ifaddresses(interface)[ni.AF_INET][0]['addr']
        return ip_address
    except (ValueError, KeyError):
        return None

def get_tun0_or_eth0_ip():
    tun0_ip = get_ip_address('tun0')
    if tun0_ip:
        return tun0_ip
    else:
        print("No tun0 IP found, checking for eth0 IP...")
        eth0_ip = get_ip_address('eth0')
        if eth0_ip:
            return eth0_ip
        else:
            return None

def read_file(file_path):
    with open(file_path, 'r') as file:
        return file.readlines()

def search_keyword(lines, keyword, lines_after=0):
    found = False
    print(keyword)
    for i, line in enumerate(lines):
        if keyword in line:
            found = True
            print(line.strip())
            for j in range(1, lines_after + 1):
                if i + j < len(lines):
                    print(lines[i + j].strip())
            if lines_after != 0:
                break
    if not found:
        print(f"Keyword '{keyword}' not found in the file.")

if __name__ == "__main__":
    ip_address = None

    # Check for -i argument
    if len(sys.argv) > 2 and sys.argv[1] == '-i':
        ip_address = sys.argv[2]
        lines = read_file(CHEATSHEET_PATH)
    else:
        # If no -i argument, attempt to get the IP address
        lines = read_file(CHEATSHEET_PATH)
        ip_address = get_tun0_or_eth0_ip()

    if ip_address:
        lines = [line.replace('$LHOST', ip_address) for line in lines]
        if len(sys.argv) > 1 and sys.argv[1] != '-i':
            keyword = sys.argv[1]
            lines_after = int(sys.argv[2]) if len(sys.argv) > 2 else 0
            search_keyword(lines, keyword, lines_after)
        else:
            # If -i was used or no keyword search, print all lines
            for line in lines:
                print(line.strip())
    else:
        print("No IP address found. Printing the cheatsheet:")
        for line in lines:
            print(line.strip())
